# Base informations for the service image
config:
  image:
    repository: positionpal/chat-service
    tag: "2.2.0@sha256:e0994e19ca2fbb8faf95661d9bc17e7f4a90be55388f58cb8a38a81ba50dcd73"
    pullPolicy: IfNotPresent

  servicename: chatservice
  replicaNumber: 2
  requiredContactPointNr: 2

  managementPort: 8558
  httpPort: 8080
  grpcPort: 5052

  akkaLicenseKey: ""
  
  resources:
    limits:
      cpu: "1"
      memory: "512Mi"
    requests:
      cpu: "0.5"
      memory: "256Mi"

# Configure the connection information for the rabbtimq service
rabbitmq:
  username: user
  password: lCZtr7Eo6xXv4PWw
  namespace: rabbitmq
  serviceName: rabbitmq
  virtualHost: /
  userServiceEventQueue: group_updates_chat_service
  port: 5672

# Configure the connection information for the cassandra service
cassandra:

  image:
    debug: true
 
  dbUser:
    user: admin
    password: password

  replicaCount: 2
  initDBConfigMap: script-db-configmap
