apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chat-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.config.httpPort }}
      targetPort: {{ .Values.config.httpPort }}
      name: http
    - protocol: TCP
      port: {{ .Values.config.grpcPort }}
      targetPort: {{ .Values.config.grpcPort }}
      name: grpc
  type: ClusterIP
  selector:
  {{- include "chat-service.labels" . | nindent  4}}